server:
  port: 9080

spring:
  application:
    name: eureka-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: "http://192.168.1.101:9080/eureka/"

  server:
    enable-self-preservation: false